export const DEFAULT_STATE = {
  cash: 0,
  retirement: 0,
  homeValue: 0,
  brokerage: 0,
  consumerDebt: 0,
  mortgage: 0,
  grossIncome: 0,
  filingStatus: 'single',
  deferral401k: 0,
  employerMatch: 0,
  healthCostMonthly: 150,
  monthlyExpenses: 3000,
  debtApr: 12,
  marketYield: 7.0,
  initialAge: 35,
};
